name: Azure Python 3.7
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.12
    - name: Install dependencies
      run: |
        make install-azure
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
